In [1]:
import numpy as np

In [4]:
"""
Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами 
та виведіть його значення.
"""

'\nСтворіть одновимірний масив (вектор) з першими 10-ма натуральними числами \nта виведіть його значення.\n'

In [5]:
A = np.array([1, 2, 3, 4, 5])
print(A)
print()

[1 2 3 4 5]



In [6]:
"""
Створіть двовимірний масив (матрицю) розміром 3x3, заповніть 
його нулями та виведіть його значення.
"""

'\nСтворіть двовимірний масив (матрицю) розміром 3x3, заповніть \nйого нулями та виведіть його значення.\n'

In [7]:
M = np.zeros((2, 3), dtype=int)
print(M)
print()

[[0 0 0]
 [0 0 0]]



In [8]:
"""
Створіть масив розміром 5x5, заповніть його випадковими цілими числами 
в діапазоні від 1 до 10 та виведіть його значення.
"""

'\nСтворіть масив розміром 5x5, заповніть його випадковими цілими числами \nв діапазоні від 1 до 10 та виведіть його значення.\n'

In [9]:
M2 = np.random.randint(0, 10, size=(5, 5))
print(M2)
print()

[[7 2 0 3 2]
 [0 4 5 5 7]
 [2 7 8 1 2]
 [7 5 8 1 6]
 [0 9 7 6 4]]



In [10]:
"""
Створіть масив розміром 4x4, заповніть його випадковими дійсними числами 
в діапазоні від 0 до 1 та виведіть його значення.
"""

'\nСтворіть масив розміром 4x4, заповніть його випадковими дійсними числами \nв діапазоні від 0 до 1 та виведіть його значення.\n'

In [11]:
M3 = np.random.random(size=(4, 4))
print(M3)
print()

[[0.70257839 0.02854623 0.71338725 0.50355821]
 [0.0759505  0.21672281 0.31295423 0.17393393]
 [0.03393328 0.13176613 0.26187238 0.76277906]
 [0.11812909 0.87293205 0.2565089  0.42697998]]



In [12]:
"""
Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими 
числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, 
віднімання та множення.
"""

'\nСтворіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими \nчислами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, \nвіднімання та множення.\n'

In [13]:
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)

print(f"Array 1: {' '.join([f'{x:2d}' for x in a])}")
print(f"Array 2: {' '.join([f'{x:2d}' for x in b])}")

# Поелементне додавання
add = a + b
print(f"Addition: {add}")

# Поелементне віднімання
sub = a - b
print(f"Subtraction: {sub}")


# Поелементне множення
mult = a * b
print(f"Multiplication: {mult}")

Array 1:  3  6  7  1  6
Array 2:  4 10  2  9  4
Addition: [ 7 16  9 10 10]
Subtraction: [-1 -4  5 -8  2]
Multiplication: [12 60 14  9 24]


In [14]:
"""
Створіть два вектори розміром 7, заповніть довільними числами та 
знайдіть їх скалярний добуток.
"""

'\nСтворіть два вектори розміром 7, заповніть довільними числами та \nзнайдіть їх скалярний добуток.\n'

In [15]:
V1 = np.random.randint(-11, 11, size=(7))
print(f"Array 1: {' '.join([f'{x:3d}' for x in V1])}")

V2 = np.random.randint(-10, 11, size=(7))
print(f"Array 1: {' '.join([f'{x:3d}' for x in V2])}")

print(f"Scalar sum: {np.dot(V1, V2)}")


Array 1:   0   5 -11   1   3   9 -10
Array 1:   4  -5  -4   7 -10   2   6
Scalar sum: -46


In [16]:
"""
Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами 
в діапазоні від 1 до 10 та перемножте їх між собою.
"""

'\nСтворіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами \nв діапазоні від 1 до 10 та перемножте їх між собою.\n'

In [17]:
# Створюємо дві матриці
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

# Виводимо матриці
print(f"Matrix 1:\n{matrix1}")
print(f"Matrix 2:\n{matrix2}")

# Перемножуємо матриці
result = np.dot(matrix1, matrix2)
print(f"Result:\n{result}")

Matrix 1:
[[2 4]
 [5 3]]
Matrix 2:
[[10  5  9]
 [ 5 10 10]]
Result:
[[40 50 58]
 [65 55 75]]


In [18]:
"""
Створіть матрицю розміром 3x3, заповніть її випадковими 
цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
"""

'\nСтворіть матрицю розміром 3x3, заповніть її випадковими \nцілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.\n'

In [19]:
matrix1 = np.random.randint(1, 11, size=(3, 3))
print(matrix1)
print()
matrix_inv = np.linalg.inv(matrix1)
print(matrix_inv)

[[ 9  7  5]
 [ 5  3  3]
 [ 7  7 10]]

[[-0.17307692  0.67307692 -0.11538462]
 [ 0.55769231 -1.05769231  0.03846154]
 [-0.26923077  0.26923077  0.15384615]]


In [20]:
"""
Створіть матрицю розміром 4x4, заповніть її випадковими 
дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
"""

'\nСтворіть матрицю розміром 4x4, заповніть її випадковими \nдійсними числами в діапазоні від 0 до 1 та транспонуйте її.\n'

In [21]:
matrix2 = np.random.random(size=(4, 4))

matrix_T = matrix2.T
print(matrix2)
print()
print(matrix_T)


[[0.94184798 0.64197525 0.78140507 0.13870342]
 [0.79723893 0.85663536 0.10619127 0.37873883]
 [0.00477266 0.4497056  0.783224   0.50718195]
 [0.23467008 0.57185836 0.96842062 0.45668175]]

[[0.94184798 0.79723893 0.00477266 0.23467008]
 [0.64197525 0.85663536 0.4497056  0.57185836]
 [0.78140507 0.10619127 0.783224   0.96842062]
 [0.13870342 0.37873883 0.50718195 0.45668175]]


In [22]:
"""
Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими
цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
"""

'\nСтворіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими\nцілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.\n'

In [23]:
# Створюємо матрицю 3x4
matrix = np.random.randint(1, 11, size=(3, 4))
print(f"Matrix:\n{matrix}")

# Створюємо вектор розміром 4
vector = np.random.randint(1, 11, size=(4))
print(f"Vector: {vector}")

# Перемножуємо матрицю на вектор
result = np.dot(matrix, vector)
print(f"Result: {result}")

Matrix:
[[8 2 6 3]
 [3 7 9 5]
 [4 7 1 5]]
Vector: [ 5  2 10  1]
Result: [107 124  49]


In [24]:
"""
Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні
від 0 до 1 та перемножте матрицю на вектор.
"""

'\nСтворіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні\nвід 0 до 1 та перемножте матрицю на вектор.\n'

In [25]:
# Створюємо матрицю 2x3
matrix2 = np.random.random(size=(2, 3))
print(f"Matrix:\n{matrix2}")

# Створюємо вектор розміром 3
vector2 = np.random.random(size=(3))
print(f"Vector: {vector2}")

# Перемножуємо матрицю на вектор
result2 = np.dot(matrix2, vector2)
print(f"Result2: {result2}")

Matrix:
[[0.89017995 0.74292447 0.97861037]
 [0.83613142 0.3781793  0.35521387]]
Vector: [0.0524119  0.34507999 0.68393603]
Result2: [0.97233129 0.41726891]


In [26]:
"""
Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні 
від 1 до 10 та виконайте їхнє поелементне множення.
"""

'\nСтворіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні \nвід 1 до 10 та виконайте їхнє поелементне множення.\n'

In [27]:
# Створюємо матрицю 2x2
matrix3 = np.random.randint(1, 11, size=(2, 2))
print(f"Matrix:\n{matrix3}")

# Створюємо матрицю 2x2
matrix4 = np.random.randint(1, 11, size=(2, 2))
print(f"Matrix:\n{matrix4}")

# Перемножуємо матриці поелементно
result3 = matrix3 * matrix4
print(f"Result: {result3}")

Matrix:
[[ 4  6]
 [10  3]]
Matrix:
[[10  7]
 [ 1 10]]
Result: [[40 42]
 [10 30]]


In [28]:
"""
Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими 
числами в діапазоні від 1 до 10 та знайдіть їх добуток.
"""

'\nСтворіть дві матриці розміром 2x2, заповніть їх випадковими цілими \nчислами в діапазоні від 1 до 10 та знайдіть їх добуток.\n'

In [30]:
# Створюємо матрицю 2x2
matrix5 = np.random.randint(1, 11, size=(2, 2))
print(f"Matrix:\n{matrix5}")

# Створюємо матрицю 2x2
matrix6 = np.random.randint(1, 11, size=(2, 2))
print(f"Matrix:\n{matrix6}")

# Перемножуємо матриці
result4 = matrix5 @ matrix6
# result3 = np.dot(matrix3, matrix4)
print(f"Result:\n{result4}")

Matrix:
[[10  7]
 [ 8  3]]
Matrix:
[[7 3]
 [7 4]]
Result:
[[119  58]
 [ 77  36]]


In [31]:
"""
Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні 
від 1 до 100 та знайдіть суму елементів матриці.
"""

'\nСтворіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні \nвід 1 до 100 та знайдіть суму елементів матриці.\n'

In [32]:
# Створюємо матрицю 5x5 з випадковими цілими числами від 1 до 100
matrix = np.random.randint(1, 101, size=(5, 5))
print(f"Matrix:\n{matrix}")

# Знаходимо суму елементів матриці
sum = np.sum(matrix)
print(f"Sum of all elements: {sum}")

Matrix:
[[46 10 10 47 52]
 [10 12 85 12 13]
 [50 38 65 98 85]
 [10 29 64 93  6]
 [24  3 16 26 61]]
Sum of all elements: 965


In [33]:
"""
Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні 
від 1 до 10 та знайдіть їхню різницю.
"""

'\nСтворіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні \nвід 1 до 10 та знайдіть їхню різницю.\n'

In [34]:
# Створюємо матрицю 4x4 з випадковими цілими числами від 1 до 10
matrix2 = np.random.randint(1, 11, size=(4, 4))
print(f"Matrix:\n{matrix2}")


# Створюємо матрицю 4x4 з випадковими цілими числами від 1 до 10
matrix3 = np.random.randint(1, 11, size=(4, 4))
print(f"Matrix:\n{matrix3}")

# difference = np.sum(matrix2) - np.sum(matrix3)

# Знаходимо поелементну різницю між матрицями
difference = matrix2 - matrix3
print(f"Difference:\n{difference}")

Matrix:
[[10  1  9  1]
 [ 6  2 10  5]
 [ 5  5  2  8]
 [ 1  3  1  7]]
Matrix:
[[ 4  3  1 10]
 [10  1  5  9]
 [ 7  5  7  7]
 [ 3  3  5  7]]
Difference:
[[ 6 -2  8 -9]
 [-4  1  5 -4]
 [-2  0 -5  1]
 [-2  0 -4  0]]


In [35]:
"""
Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами 
в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
"""

'\nСтворіть матрицю розміром 3x3, заповніть її випадковими дійсними числами \nв діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.\n'

In [36]:
# Створимо матрицю 3x3 з випадковими числами від 0 до 1
matrix = np.random.random((3, 3))
print(f"Original matrix:\n{matrix}")

# Ініціалізуємо порожній список для зберігання сум рядків
row_sums = []

# Проходимося по кожному рядку матриці та сумуємо його елементи
for row in matrix:
    row_sum = np.sum(row)
    row_sums.append(row_sum)

# Преобразуємо список в numpy масив та робимо його двовимірним (вектор-стовпчик)
row_sums = np.array(row_sums).reshape(-1, 1)
print(f"Row sums:\n{row_sums}")

Original matrix:
[[0.25874052 0.22661702 0.91134493]
 [0.38091992 0.57903031 0.24127733]
 [0.26452879 0.58637875 0.8029833 ]]
Row sums:
[[1.39670247]
 [1.20122755]
 [1.65389084]]


In [37]:
"""
Створіть матрицю розміром 3x4 з довільними цілими числами 
і створінь матрицю з квадратами цих чисел.
"""

'\nСтворіть матрицю розміром 3x4 з довільними цілими числами \nі створінь матрицю з квадратами цих чисел.\n'

In [38]:
# Створюємо матрицю 3x4 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(3, 4))
print(f"Matrix:\n{matrix}")

# Створюємо матрицю з квадратами чисел
matrix2 = matrix**2

print(f"New matrix is:\n{matrix2}")

Matrix:
[[1 6 5 8]
 [8 7 1 9]
 [6 9 6 9]]
New matrix is:
[[ 1 36 25 64]
 [64 49  1 81]
 [36 81 36 81]]


In [39]:
"""
Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні 
від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
"""

'\nСтворіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні \nвід 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.\n'

In [40]:
# Створюємо вектор розміром 4 з випадковими цілими числами від 1 до 50
vector = np.random.randint(1, 51, size=(4))
print(f"Original vector: {vector}")

# Знаходимо квадратні корені елементів вектора
# sqrt_vector = np.sqrt(vector)
sqrt_vector = np.round(np.sqrt(vector), 4)
print(f"Vector of square roots: {sqrt_vector}")

Original vector: [18 23 39 48]
Vector of square roots: [4.2426 4.7958 6.245  6.9282]
